### ISSUE TITLE
React/Redux improvements

### ISSUE THREAD

**Issue by cjcenizal** [elastic/kibana-ui-framework#18]
Per discussion with @kjbekkelund:
- We can improve the way the title is defined, by specifying `onEnter` and `onChange` handlers per route. The `onEnter` handler accepts a routerState argument, and `onChange` accepts `currentState` and `nextState` arguments. These can be used to extract the title from the current/next route.
- Because context is an "unstable" feature, we can use containers to instead provide actions directly to the components which need them, `GuidePageSection` and `GuideExample` for example.
- We can remove empty constructors from components and convert some of them into stateless functional components.
- Component examples should compose `GuideExample` by passing in `sections` as a prop, instead of inheriting it.
- Inside of `GuideExample`, we can decorate the `sections` in the render function instead of the constructor or lifecycle hook. This shouldn't affect performance.

**Comment by kjbekkelund** [comment]
Btw, `onEnter` and `onChange` are not _per_ route, you can do it at the top-level (and therefore specify the functions _only_ once)
